### ISSUE TITLE
Make interior, ground, wall, and ceiling tiles

### ISSUE THREAD

**Issue by lgibbs-eps** [lgibbs-eps/EPS-Game-Dev-Club#5]
Something formatted like:
![image](https://user-images.githubusercontent.com/36085900/47610674-3a76db80-da10-11e8-9503-e9d72122c6f5.png)
In roughly the style of:
![image](https://user-images.githubusercontent.com/36085900/47610681-59756d80-da10-11e8-86fd-e75ce84d2931.png)
or
![image](https://user-images.githubusercontent.com/36085900/47610678-4d89ab80-da10-11e8-81a4-f70d2dee4e2b.png)
or
![image](https://user-images.githubusercontent.com/36085900/47610687-685c2000-da10-11e8-8014-71506505cae5.png)
in order of preference.

**Comment by flufflaire** [comment]
![compiled and rotated tileset](https://user-images.githubusercontent.com/31524896/49044285-1c70d800-f182-11e8-979e-a4ad44c72b87.png)
