### ISSUE TITLE
Learn Zero Engine (Albert)

### ISSUE THREAD

**Issue by lgibbs-eps** [lgibbs-eps/EPS-Game-Dev-Club#6]
Albert needs to complete these Zero Engine Tutorials:
Events I and II
Collisions
Archetypes I and II
Tile Editor I and II
Sprite Animations
Keyboard Input
Actions
Arrays

**Comment by hyperac** [comment]
Finished Events, Collisions, and am familiar with Keyboard Input. Will work on Actions, Arrays, Archetypes tonight. Will do Sprite Animations when Calvin gives us his sprite (he says he's gonna redraw it to match the style of the "tileset").
