### ISSUE TITLE
Learn Zero Engine (Fay)

### ISSUE THREAD

**Issue by lgibbs-eps** [lgibbs-eps/EPS-Game-Dev-Club#7]
Fay needs to complete these Zero Engine Tutorials:
Events I and II
Collisions
Archetypes I and II
Tile Editor I and II
Sprite Animations
Keyboard Input
Actions
Arrays

**Comment by flufflaire** [comment]
Finished Tutorial Sequences Beginner 1.1 & 1.2
Total time is estimated to be _*a looong time*_ to learn zero engine completely.

**Comment by lgibbs-eps** [comment]
We don't need completely right now. You just basically need to know how to make what I have made so far, and maybe also some more stuff about tile sets and animations. You don't really need to _know_ zero engine, you should just be comfortable with the basics.
